FROM resin/rpi-raspbian:jessie-20160831
RUN apt-get update && apt-get install -y python3 python3-pip nginx nano curl && apt-get clean
RUN curl -sSL https://get.docker.com/ | sh
RUN mkdir -p /usr/bin/asmp

COPY src/requirements.txt /usr/bin/asmp/requirements.txt
RUN pip3 install -r /usr/bin/asmp/requirements.txt 

COPY src /usr/bin/asmp/
COPY src/data/db_clean.sqlite3 /usr/bin/asmp/db.sqlite3
VOLUME /usr/bin/asmp/data

ARG VERSION=unkown
LABEL application=asmp component=updater environment=linarm version=$VERSION

CMD ["/usr/bin/asmp/updater/start.sh"]