FROM resin/rpi-raspbian:jessie-20160831
RUN apt-get update && apt-get install -y python3 python3-pip nginx
RUN mkdir -p /usr/bin/asmp
COPY src /usr/bin/asmp/
COPY src/data/db.sqlite3 /usr/bin/asmp/db.sqlite3
COPY src/asmp.nginxconf /etc/nginx/sites-available/asmp
CMD ["ln -s /etc/nginx/sites-available/asmp /etc/nginx/sites-enabled/asmp"]
VOLUME /usr/bin/asmp/data
RUN pip3 install -r /usr/bin/asmp/requirements.txt 
EXPOSE 8000
CMD ["/usr/bin/asmp/start-arm.sh"]