# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metermeasurement',
            old_name='meter_id',
            new_name='meter',
        ),
    ]
