# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='timestamp_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='timestamp_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
