# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161221_0804'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meter',
            table='Meter',
        ),
        migrations.AlterModelTable(
            name='metermeasurement',
            table='MeterMeasurement',
        ),
    ]
