# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170412_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='aggregated',
            field=models.BooleanField(default='0'),
        ),
    ]
