# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170418_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('level', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
