# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_measurement_aggregated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usage_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('return_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estimated', models.BooleanField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Meter')),
            ],
            options={
                'db_table': 'Statistic',
            },
        ),
    ]
