FROM debian:jessie
RUN apt-get update && apt-get install -y python3 python3-pip nginx nano curl && apt-get clean
RUN mkdir -p /usr/bin/asmp

COPY src/requirements.txt /usr/bin/asmp/requirements.txt
RUN pip3 install -r /usr/bin/asmp/requirements.txt 

COPY src /usr/bin/asmp/
VOLUME /usr/bin/asmp/data

ARG VERSION=unkown
LABEL application=asmp component=aggregator environment=lin64 version=$VERSION

CMD ["/usr/bin/asmp/aggregator/start.sh"]