# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'Setting',
            },
        ),
    ]
