# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171217_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='usage_current',
            new_name='power_usage_current',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='usage_total_low',
            new_name='power_usage_total_low',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='usage_total_normal',
            new_name='power_usage_total_normal',
        ),
    ]
