# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171217_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='power_return_current',
            new_name='power_supply_current',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='power_return_total_low',
            new_name='power_supply_total_low',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='power_return_total_normal',
            new_name='power_supply_total_normal',
        ),
    ]
