# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171217_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='gas_usage_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='measurement',
            name='gas_using_now',
            field=models.BooleanField(default=0),
        ),
    ]
