# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171217_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='return_end',
            new_name='power_return_end',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='return_start',
            new_name='power_return_start',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='usage_end',
            new_name='power_usage_end',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='usage_start',
            new_name='power_usage_start',
        ),
    ]
