# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171217_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='power_return_end',
            new_name='power_supply_end',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='power_return_start',
            new_name='power_supply_start',
        ),
    ]
